config/routes.rb
Rails.application.routes.draw do
  resources :flows
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flow.rb
class Flow < ApplicationRecord
    belongs_to :user
    validates :item, presence: true
    validates :value, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :flows
    validates :username, presence: true,
                         uniqueness: { case_sensitive: false },
                         length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true,
                         uniqueness: { case_sensitive: false },
                         length: { maximum: 105 },
                         format:{ with: VALID_EMAIL_REGEX }
    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flows_controller.rb
class FlowsController < ApplicationController
  before_action :set_flow, only: %i[ show edit update destroy ]

  # GET /flows or /flows.json
  def index
    @flows = Flow.all
  end

  # GET /flows/1 or /flows/1.json
  def show
  end

  # GET /flows/new
  def new
    @flow = Flow.new
  end

  # GET /flows/1/edit
  def edit
  end

  # POST /flows or /flows.json
  def create
    @flow = Flow.new(flow_params)
    @flow.user = User.first
    respond_to do |format|
      if @flow.save
        format.html { redirect_to flow_url(@flow), notice: "Flow was successfully created." }
        format.json { render :show, status: :created, location: @flow }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flows/1 or /flows/1.json
  def update
    respond_to do |format|
      if @flow.update(flow_params)
        format.html { redirect_to flow_url(@flow), notice: "Flow was successfully updated." }
        format.json { render :show, status: :ok, location: @flow }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flows/1 or /flows/1.json
  def destroy
    @flow.destroy

    respond_to do |format|
      format.html { redirect_to flows_url, notice: "Flow was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flow
      @flow = Flow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flow_params
      params.require(:flow).permit(:item, :value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flows_helper.rb
module FlowsHelper
end

app/views/flows/_flow.html.erb
<div id="<%= dom_id flow %>" class="item-container">
  <p>
    <strong>Item:</strong>
    <%= flow.item %>
  </p>
  <p class="value-container">
    <strong>Value:</strong>
    <%= number_to_currency(flow.value, unit: "R$", separator: ",", delimiter: ".") %>
  </p>
</div>

app/views/flows/_form.html.erb
<%= form_with(model: flow) do |form| %>
  <% if flow.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(flow.errors.count, "error") %> prohibited this flow from being saved:</h2>

      <ul>
        <% flow.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :item, style: "display: block" %>
    <%= form.text_field :item %>
  </div>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.text_field :value %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/flows/edit.html.erb
<h1>Editing flow</h1>

<%= render "form", flow: @flow %>

<br>

<div>
  <%= link_to "Show this flow", @flow %> |
  <%= link_to "Back to flows", flows_path %>
</div>

app/views/flows/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Flows</h1>

<div id="flows">
  <% @flows.each do |flow| %>
    <%= render flow %>
    by <%= flow.user.username if flow.user %>
    <p>
      <%= link_to "Show this flow", flow %>
    </p>
  <% end %>
</div>

<%= link_to "New flow", new_flow_path %>

app/views/flows/new.html.erb
<h1>New flow</h1>

<%= render "form", flow: @flow %>

<br>

<div>
  <%= link_to "Back to flows", flows_path %>
</div>

app/views/flows/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @flow %>
by <%= @flow.user.username if @flow.user %>
<div>
  <%= link_to "Edit this flow", edit_flow_path(@flow) %> |
  <%= link_to "Back to flows", flows_path %>

  <%= button_to "Destroy this flow", @flow, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>